name: resoclean
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^2.0.2
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  dio: ^3.0.10
  equatable: ^1.2.5
  flutter_mobx: ^1.1.0+2
  get_it: ^5.0.4
  mobx: ^1.2.1+4
  shared_preferences: ^0.5.12+4

dev_dependencies:
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.13
  mockito: ^4.1.3
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
